### ISSUE TITLE
Panning not working on iPad

### ISSUE THREAD

**Issue by mpschaeuble** [BALKANGraph/OrgChartJS#51] opened 2019-03-22 15:46 UTC
Panning does not work on iPad's.

**Comment by BALKANGraph** [comment] 2019-03-22 15:49
Thank you for reporting this issue

It will be fixed in the next version

**Comment by BALKANGraph** [comment] 2019-04-06 23:57
The issue is fixed in the latest release 4.5.0

Now OrgChart JS works well on iphone and ipad

**Closed** 2019-11-21 18:14 UTC
Labels: bug, fixed
