### ISSUE TITLE
Node add changed

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#410] opened 2020-07-15 11:09 UTC
After upgrade to version 7, the behaviour when creating a node with the method add has changed. If the parent node is expanded, the new node is collapsed after creation. In version 6 the new node was expanded after creation. This change is a problem for us.

**Comment by sks4u** [comment] 2020-07-22 10:23
Can you please give me a status of this issue? Thank you

**Comment by plamen-peshev** [comment] 2020-07-23 14:14
The issue is fixed in version 7.1.6

Here is a demo: https://jsfiddle.net/5wdv8smc/1/

Clear your browser cache before test

**Comment by sks4u** [comment] 2020-07-31 11:02
I have installed 7.1.95. The issue is still there.

**Comment by ZornitsaSerbezova** [comment] 2020-08-03 10:38
Hi sks4u,
In the example above the nodes are expanded on add. Isn't this what you wanted?

**Comment by sks4u** [comment] 2020-08-10 15:20
The example behaves as I have requested. However, the OrgChart in my application behaves differently. There a newly added item is in collapsed state. I often have the problem that your examples behave differently in JSFiddle than in my Angular application. I can't tell you why this is the case. I have made a movie to illustrate this.
[AddNode.zip](https://github.com/BALKANGraph/OrgChartJS/files/5051667/AddNode.zip)

**Comment by ZornitsaSerbezova** [comment] 2020-08-11 08:15
Could you try to reproduce the issue in jsfiddle, because I have tried it in an Angular project, but it was working as expected, so we have to look for the problem in your code?

**Comment by sks4u** [comment] 2020-08-18 15:19
I cannot reproduce the problem in jsfiddle. But I wonder how it could be that the problem is due to my application? Can I do something wrong so that the OrgChart behaves so different? Unfortunately I can't provide an Angular sample application either. I have done this before for another issue, but you didn't get it to work.

**Comment by ZornitsaSerbezova** [comment] 2020-08-20 10:39
Hi sks4u,

I have managed to run the other project, but still have not found the issue,
Please create a project with this issue also, but please isolate in the code that is needed to reproduce this issue only.

**Comment by ZornitsaSerbezova** [comment] 2020-08-24 09:21
Thank you for reproducing the issue. We will try to fix it soon.

**Comment by sks4u** [comment] 2020-09-01 16:23
Still waiting for a fix.

**Comment by ZornitsaSerbezova** [comment] 2020-09-03 07:58
Hi sks4u,

We haven't forgotten, but haven't fixed this yet.

**Comment by plamen-peshev** [comment] 2020-09-07 08:56
We have addressed the issue in version 7.3.47

**Comment by plamen-peshev** [comment] 2020-09-08 08:21
We have rollbacked the change as it cause other issues

you can use:
`chart.addNode(n); `
or 
```
chart.add(n); 
chart.draw(OrgChart.action.insert, { id: n.pid, insertedNodeId: n.id }); 
```

instead of 

```
chart.add(n);
chart.draw(OrgChart.action.insert, { id: n.pid, insertedNodeId: n.id });
```

**Comment by sks4u** [comment] 2020-09-18 07:30
I'm afraid using the addNode method instead of the add method will not work for us. It happens that we add hundreds of nodes. This takes a very long time with the addNode method compared to the add method. 

The other workaround you describe contains an undocumented call to the draw method. Does it have to be executed after each call to the add method? In this case I do not expect any improvement in performance. Or can I pass multiple nodes and then execute the draw method after several calls to the add method?

**Comment by ZornitsaSerbezova** [comment] 2020-09-21 11:26
Hi sks4u,

You could try this in your case:
```
chart.add(n1).add(n2);
chart.draw();
chart.expand(id, [n1.id, n2.id])
```

**Comment by sks4u** [comment] 2020-09-23 09:16
This workaround does not work for me because of error #462

**Comment by plamen-peshev** [comment] 2020-09-24 09:28
Created a demo for you https://jsfiddle.net/BALKANGraph/a2tkxLu3/

**Comment by sks4u** [comment] 2020-09-25 07:22
I'm sorry, but this example is not helpful. In my application I add nodes at different places. Some of the patent nodes are not visible at all. If I now call expand on this nodes, I get an error (see #462). So I have to check first if the parent node is expanded. But I can't do that, because you don't want to tell me how to find out if the parent node is expanded (see #407).

**Comment by ZornitsaSerbezova** [comment] 2020-09-25 08:53
Hi sks4u,

We have edited the example.

Is this not working for you:

```
            document.getElementById("btn").addEventListener("click", function () {                
                chart.add(n[0]).add(n[1]);
                chart.draw(null, null, function(){
                    if (chart.getNode(2).collapsed)
                    chart.expand(1, [n[0].id, n[1].id, 2]);                  
                    else chart.expand(2, n[0].id, n[1].id);                    
                });
            });
```

**Comment by sks4u** [comment] 2020-09-25 14:24
Please read #407. The problem is, that in the real world the collapsed property can return 'undefined' and I do not know how to interpret the value 'undefined'.

Beside of this, the node should only be expanded, if the neighboring nodes are expanded too. Therefore I need the exact collapsed state.

**Comment by sks4u** [comment] 2020-09-25 14:28
I also don't understand why in the example node 1 is passed as first parameter of the expand function. I understood that you have to pass the parent node there. Is it possible to simply pass any node there?

**Comment by ZornitsaSerbezova** [comment] 2020-09-27 12:39
If **node.collapsed** is false or undefined, then it is not collapsed. You need to check **node.parent**, until you find the collapsed node and expand it. You could get parent from **nodes**.

If the parent is expanded and the siblings are collapsed, they will return true on node.collapsed.

1 is passed because the passed because we are sure that it is expanded.

**Comment by ZornitsaPesheva** [comment] 2021-11-04 12:49
I'll close this issue as it looks inactive. Feel free to reopen it with a particular question, if you need.

**Closed by ZornitsaPesheva** 2021-11-04 12:49 UTC
Labels: fixed
