### ISSUE TITLE
export for png doesn't work  correctly

### ISSUE THREAD

**Issue by yingliufengpeng** [BALKANGraph/OrgChartJS#101] opened 2019-05-22 05:00 UTC
when i export png it occurs somewrong beflow 

![image](https://user-images.githubusercontent.com/11833630/58148495-99908c00-7c91-11e9-87db-4187dc8f7787.png)

**Comment by webcall-me** [comment] 2019-05-22 06:02
Very strange

For me it works like a charm

What is you code configuration

**Comment by yingliufengpeng** [comment] 2019-05-22 06:15
In the attachment is a pdf that i want use, but exported png  is display part,  is there some way to fix it?

**Comment by yingliufengpeng** [comment] 2019-05-22 06:18
![image](https://user-images.githubusercontent.com/11833630/58151472-5ee02100-7c9c-11e9-8e02-cc68f3f669e6.png)

this is my configuration

**Comment by webcall-me** [comment] 2019-05-22 06:18
What is not working, PNG or PDF export

Can you create a demo in jsfiddle?

**Comment by yingliufengpeng** [comment] 2019-05-22 06:21
wow, the same view ,  when i export pdf, i will export correctly,  but png, it is export Partially!

![部门组织架构 (24)](https://user-images.githubusercontent.com/11833630/58151651-dada6900-7c9c-11e9-94c9-1410309e36a1.png)
[OrgChart (1).pdf](https://github.com/BALKANGraph/OrgChartJS/files/3205887/OrgChart.1.pdf)

**Comment by yingliufengpeng** [comment] 2019-05-22 06:29
In my test, when nodes are bigger, a exported png  is rendered partially

**Comment by yingliufengpeng** [comment] 2019-05-22 06:41
Is any solution to  solve  this?

**Comment by webcall-me** [comment] 2019-05-22 06:44
Can you please test [this](https://balkangraph.com/OrgChartJS/Demos/Tab/Exporting) demo and confirm that is working for you

Also you can modify the demo with your code

**Comment by yingliufengpeng** [comment] 2019-05-22 06:59
this demo[https://jsfiddle.net/nmu21ecv/2/](url)

**Comment by yingliufengpeng** [comment] 2019-05-22 07:22
this is issue could be resolved  recently?

**Comment by plamen-peshev** [comment] 2019-05-22 10:24
Thanks for the demo

We were able to replicate the issue

It will be addressed in one of the following versions

**Comment by yingliufengpeng** [comment] 2019-05-23 00:27
it's my pleasure, hope it very well

**Comment by ZornitsaSerbezova** [comment] 2020-05-27 17:30
The issue is addressed in the latest export service v1.3.9

**Closed** 2020-06-03 07:14 UTC
Labels: bug
