### ISSUE TITLE
Incorrect position of the main node 

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#307] opened 2020-01-24 18:48 UTC
Incorrect position of the main node using Group Assistent nodes and Assistent out of group at the same time.

![wrong_position_main_node](https://user-images.githubusercontent.com/2631583/73095238-e4b60b00-3ec0-11ea-88b1-2a9dfe9ef787.png)

**Comment by plamen-peshev** [comment] 2020-01-29 11:31
The issue is fixed in version 6.1.998

**Closed** 2020-07-06 15:31 UTC
