### ISSUE TITLE
PDF preview missing pages/content depending on margins

### ISSUE THREAD

**Issue by Marika273** [BALKANGraph/OrgChartJS#325] opened 2020-02-17 20:30 UTC
Hi,

I have a problem with the PDF preview. Depending on the top and bottom margins, the nodes are cut/not displayed properly. I tested the issue in your demo (https://balkangraph.com/OrgChartJS-Demos/Exporting) and the problem is also there.

Here is the issue:
![issue](https://user-images.githubusercontent.com/61164477/74684031-b4e4e500-5198-11ea-8bf9-604435334ea5.PNG)

I expected to see a second page with the missing content, but there is only one page. Even when there is a second page, there is still missing content as you can see here (the names of the 2 nodes at the bottom are missing):
![image](https://user-images.githubusercontent.com/61164477/74684137-1d33c680-5199-11ea-8e1a-9139e2fb2c7b.png)

Is there a way to fix this?

Thanks.

**Comment by ZornitsaSerbezova** [comment] 2020-02-19 09:25
Hi Marika273,
Thank you for reporting this issue. We will fix it and will let you know.

**Comment by ZornitsaSerbezova** [comment] 2020-06-03 06:59
Hi Marika273,
The issue is fixed in the latest version (6.6.2).

**Closed** 2020-07-06 15:38 UTC
