### ISSUE TITLE
_img2base64 returns callback early

### ISSUE THREAD

**Issue by ZackHJ** [BALKANGraph/OrgChartJS#271] opened 2019-11-14 21:20 UTC
In some cases when exporting the org chart, some images will not be rendered correctly. 
I think the cause of such issue is in the following function.
```javascript
OrgChart._imgs2base64 = function (el, tag, attr, callback) {
    var images = el.getElementsByTagName(tag);
    var count = images.length;
    if (count == 0){
        callback();
    }
    for (var i = 0; i < count; i++) {                
        (function () {
            var index = i;
            var image = images[index];
            OrgChart._getDataUri(image.getAttribute(attr), function (res) {
                if (res.success) {
                    image.setAttribute(attr, res.result);
                }
                if (index == (count - 1)) {
                    callback();
                }
            });
        })();
    }
}
```

The callback is invoked when `index == (count - 1)` is met, however there is a racing issue regarding when the callback from `_getDataUri` is returned.
For instance, if I have 2 images, where the first image is a url to a slow server, and the second image is already encoded in base64, then the second call on `_getDataUri` will be returned before the first call. At this point, the condition `index == (count - 1)` is met, and callback is invoked before the first image is finished encoding.

I think #247 is related to this.

**Comment by plamen-peshev** [comment] 2019-11-18 11:31
Thanks for reporting this issue

We have logged it

**Comment by plamen-peshev** [comment] 2019-12-12 16:42
The issue is fixed in the latest version

**Closed** 2019-12-12 16:42 UTC
Labels: bug, fixed
