### ISSUE TITLE
Message: Added non-passive event listener to a scroll-blocking 'mousewheel' event. 

### ISSUE THREAD

**Issue by uumi95** [BALKANGraph/OrgChartJS#358] opened 2020-05-11 05:56 UTC
Hello,
In the orgchart, when I click on a function this msg is displayed according to the number of nodes, and because of this unstable orgchart, is there a solution?
 **MSG: orgchart.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.**
<img width="538" alt="AA" src="https://user-images.githubusercontent.com/38526134/81528178-9fbcc400-934b-11ea-9928-a119bd0789b4.png">

Thank you !

**Comment by ZornitsaSerbezova** [comment] 2020-05-11 11:11
Hi uumi95,
Could you isolate an jsfiddle example with this issue?

Regards,
Zornitsa

**Comment by uumi95** [comment] 2020-05-18 02:19
I did not find a space in jsfiddle where I can create my C # code to show you the error, because i am using a read function to retrieve data with jquery

**Comment by lindsoe** [comment] 2020-05-23 17:31
For an example: The demo  https://balkangraph.com/OrgChartJS-Demos/CenterOnAdd  shows the message,  when add-event is triggered

**Comment by plamen-peshev** [comment] 2020-05-27 18:55
The issue is addressed in version 6.4.2

**Closed** 2020-07-07 12:40 UTC
Labels: fixed
