### ISSUE TITLE
Export Issues

### ISSUE THREAD

**Issue by mi0o** [BALKANGraph/OrgChartJS#291] opened 2019-12-06 13:51 UTC
Hi I have various issues with export>

1 ) is there any export limit?
when I export wide structure it cut the right side off 
![image](https://user-images.githubusercontent.com/7822505/70327574-62518900-1837-11ea-8f3b-465c08f78308.png)

2) In Scenario 2. It export from last node some equal node. It should export only child, but if it is last node there should export just one cell
![image](https://user-images.githubusercontent.com/7822505/70327218-94162000-1836-11ea-9f11-8c7841cccb16.png)

but it doesnt
![image](https://user-images.githubusercontent.com/7822505/70327779-d5f39600-1837-11ea-8c8e-c992b883c94d.png)

But in other cases it works ok. 

Simulation:  [link](https://srv-file4.gofile.io/download/41anUh/test.html)
Search for scenario 1, scenario 2. And use your own orgchart.js

**Comment by ZornitsaSerbezova** [comment] 2019-12-09 10:06
Hi **mi0o**,

Your link is not working. Could you, please create examples in jsfiddle?

**Comment by mi0o** [comment] 2019-12-09 10:11
Hi

It was too big for JsFiddle. And unable to load paid orgstruct.js library.
More then 200 nodes.
So you can see attached file.

Thanks
Michal

**Comment by mi0o** [comment] 2019-12-09 10:14
Hi
I forwarded mail to Plemen because of attachment. 

Michal

**Comment by plamen-peshev** [comment] 2019-12-10 08:38
I must admit that it is an issue in the export

We will fix it as soon as we can

**Comment by mi0o** [comment] 2019-12-11 09:55
Hi,

thanks, let me know.

Michal

**Comment by mi0o** [comment] 2020-01-02 09:51
hallo, anything new in this issue? 

Thanks a lot

**Comment by mi0o** [comment] 2020-01-14 07:10
Hello I havent hear from you for a while. 
Is something happen with this issue?

**Comment by plamen-peshev** [comment] 2020-01-24 09:29
The issue turns out to be more complicated that we initially thought, the export service depends on third party component provided by google

**Comment by mi0o** [comment] 2020-02-04 12:48
Hello, 
do you have some news? Or could you estimate some fix date ? 

Michal

**Comment by mi0o** [comment] 2020-03-03 13:54
hello, 
I haven't heard from you for a while. Please could you give me response? We paid for this library but it is use less for us with this issue and we don't even know it it will be fixed.

**Comment by srimathigopi12** [comment] 2020-05-26 04:58
Hello, 
Do you have any updates, I also have same error

**Comment by plamen-peshev** [comment] 2020-05-27 16:25
The issue is addressed in the latest export service v1.3.9

If you are using the default export service no actions are required

**Comment by mi0o** [comment] 2020-05-27 16:30
Can we report that to the google ?


Dňa st 27. 5. 2020, 18:25 Plamen Peshev <notifications@github.com>
napísal(a):

**Comment by ZornitsaSerbezova** [comment] 2020-07-06 15:07
This issue is fixed, so I'll close it. Feel free to reopen it explaining what is the problem if needed.

**Closed by ZornitsaSerbezova** 2020-07-06 15:07 UTC
Labels: bug, fixed
