### ISSUE TITLE
linkAdjuster for Slink Template

### ISSUE THREAD

**Issue by kafai39** [BALKANGraph/OrgChartJS#425] opened 2020-08-11 04:18 UTC
Hello,
How can I adjust the slink template position like the linkAdjuster? Or put the slink behind the node?
Thank you!

**Comment by ZornitsaSerbezova** [comment] 2020-08-11 08:01
Hi kafai39,

Do you mean C link and this?:

![image](https://user-images.githubusercontent.com/19305472/89872638-e8da1980-dbc1-11ea-9c9e-5fee79e52a26.png)

**Comment by kafai39** [comment] 2020-08-11 08:12
When I using the slinks with node sublevels. The slink will overlap the node.

![Screen Shot 2020-08-11 at 4 08 50 PM](https://user-images.githubusercontent.com/6768128/89873576-3c159180-dbed-11ea-911c-5db43c720791.png)

**Comment by ZornitsaSerbezova** [comment] 2020-08-12 15:33
Hi kafai39,

Could you create an example in jsfiddle with S links that overlap, because we couldn't reproduce the issue?

**Comment by kafai39** [comment] 2020-08-13 02:26
Hi ZornitsaSerbezova,

jsfiddle example link: https://jsfiddle.net/kafai39/nwoxL7ca/2/

![Screen Shot 2020-08-13 at 10 26 07 AM](https://user-images.githubusercontent.com/6768128/90087472-7008c800-dd4f-11ea-8a65-2030bbf5046d.png)

**Comment by ZornitsaSerbezova** [comment] 2020-08-14 08:45
Hi kafai39,

It looks like this is an issue and we have started to work on it.

**Comment by kafai39** [comment] 2020-08-20 01:58
It is grateful if you can fix it.

**Comment by kafai39** [comment] 2020-08-31 03:28
> Hi kafai39,
> 
> It looks like this is an issue and we have started to work on it.

Any good news for this issue?

**Comment by ZornitsaSerbezova** [comment] 2020-09-01 08:01
Hi kafai39,

We are still working on this and will contact you when we have any news.

**Comment by kafai39** [comment] 2020-10-05 07:14
Sorry to brother you guys again. Is it have any updates for this issue?

**Comment by ZornitsaSerbezova** [comment] 2020-10-05 07:24
Hi kafai39,

We haven't forgotten you, but haven't still fixed this, because we are working on issues with higher priority,
Thank you for your patience.

**Comment by Shubham994** [comment] 2021-02-10 09:07
Is there any features to add multiple nodes inside the single node. If it is there please provide the JS Fiddle link for that or code related to that.

Please check below image for the reference.

https://user-images.githubusercontent.com/63347370/107488481-6c92b400-6bad-11eb-8c5a-77d2795d1017.jpeg

**Comment by ZornitsaSerbezova** [comment] 2021-02-10 09:14
@Shubham994 If i usnderstand, you'd like to open childrens on clicking of 03, 04 or 05.
You can do that by defining such fields and expanding that nodes on clicking of the fields.
Or it's better to post a new issue givimg more screenshots of what exactly do you need, because this one is totally different.

**Comment by plamen-peshev** [comment] 2022-02-04 14:58
The has been addressed in the latest version 8.02.22

https://code.balkan.app/Preview/org-chart-js/slink-with-sublevels-fix#JS

**Closed** 2022-08-08 08:14 UTC
Labels: fixed
