### ISSUE TITLE
ZOom on iPad

### ISSUE THREAD

**Issue by mdcleaver** [BALKANGraph/OrgChartJS#68] opened 2019-04-05 09:40 UTC
Hi there. 
I have just been sent a link to an organogram but it doesn't work on my iPad. Here it is: https://www.voltnederland.org/organogram

**Comment by BALKANGraph** [comment] 2019-04-06 23:57
The issue is fixed in the latest release 4.5.0

Now OrgChart JS works well on iphone and ipad

**Closed** 2019-11-28 13:26 UTC
Labels: bug, fixed
