### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by mi0o** [BALKANGraph/OrgChartJS#284] opened 2019-11-27 13:21 UTC
Hello,
I notice that something has changed in export. 
in the main menu use export to PNG like this > 	menu: {png: { text: "Export PNG" }},

But few days ago it exported exactly what I have had on the screen. Now it export default structure - what I see when I refresh the web.  First line for example. why?

**Comment by mi0o** [comment] 2019-11-29 10:50
Hello,
any ideas?

**Comment by ZornitsaSerbezova** [comment] 2019-12-02 13:30
The issue is addressed in the new version.

**Closed by ZornitsaSerbezova** 2019-12-02 13:30 UTC
