### ISSUE TITLE
Move node buggy, tested with drag and drop.

### ISSUE THREAD

**Issue by MangioneAndrea** [BALKANGraph/OrgChartJS#356] opened 2020-05-05 10:09 UTC
Date of Report Submission: 05.05.2020

Data affected:				Not relevant
Workaround known:		No
Functionality affected:		Move node, Drag and drop, Add node

Description / Summary Description: If you try to move a node into a group, the GUI messes up the order and creates 2 roots
Steps to Reproduce: 
go to https://balkangraph.com/OrgChartJS/Docs/DragAndDrop
play with the second example

![ezgif-2-49e7bba4a9e5](https://user-images.githubusercontent.com/35958935/81055415-f009d100-8ec8-11ea-96ba-342f7ee2e7f1.gif)

I also tested locally to remove and re-add the node, but the result is the same.

**Comment by ZornitsaSerbezova** [comment] 2020-05-06 10:12
Hi MangioneAndrea,
Thank you for reporting this. The problem with the overlapping is a real issue, but the creating of two roots is expected behavior, because Billy Moore is the root node with id = 1 and all other nodes are under this node. So when you move this node, you change the structure of the chart,
To prevent this to happen, you could use **drag** and **drop** events with **return false**.: https://balkangraph.com/OrgChartJS/Docs/APIReference#drag

**Comment by MangioneAndrea** [comment] 2020-05-06 20:59
Here you have one more example of buggy move node. I've found many others, but those are a bit harder to follow, whereas you need to move multiple nodes to see the weird behaviour.

![ezgif-3-81cc086d02a5](https://user-images.githubusercontent.com/35958935/81227332-8be02d80-8fec-11ea-9efe-d81e3d3a9e56.gif)

**Comment by ZornitsaSerbezova** [comment] 2020-05-07 20:29
Hi MangioneAndrea,
We have logged this issue. Thank you for reporting it!

Regards,
Zornitsa

**Comment by ZornitsaSerbezova** [comment] 2020-07-07 12:39
Hi MangioneAndrea, We have complete new implamentation of groups. I'll close this issue, because it is not actual anymore.

**Closed by ZornitsaSerbezova** 2020-07-07 12:39 UTC
