### ISSUE TITLE
Customize templates

### ISSUE THREAD

**Issue by sujasuji** [BALKANGraph/OrgChartJS#329] opened 2020-03-02 07:25 UTC
How to customize predefined templates in angular. As mentioned in documentation, it is throwing error.

**Comment by ZornitsaSerbezova** [comment] 2020-03-02 09:09
Hi sujasuji,
The issue is fixed. Please download the latest version of OrgChart JS - 6.2.59.

**Comment by sujasuji** [comment] 2020-03-02 09:48
> Hi sujasuji,
> The issue is fixed. Please download the latest version of OrgChart JS - 6.2.59.

How to install latest version using npm?

**Comment by ZornitsaSerbezova** [comment] 2020-03-02 10:47
May be you can just reinstall it using the same command: npm i @balkangraph/orgchart.js
Actually it is enough to download the [package ](https://balkangraph.com/OrgChartJS/Download/DownloadEvaluate) and replace only the orgchart.d.ts file in your project.

**Comment by sujasuji** [comment] 2020-03-03 06:00
Is it possible to use bootstrap or any style library for customizing nodes?

**Comment by ZornitsaSerbezova** [comment] 2020-03-03 06:58
Hi sujasuji, 
for customizing nodes you need to use our documentation: https://balkangraph.com/OrgChartJS/Docs/CreatingCustomTemplate

**Comment by sujasuji** [comment] 2020-03-03 07:34
Yes i am following documentation but am not able to use other html elements like div, span and styling libraries like bootstrap.. 
Does orgchart supports above requirements?

**Comment by plamen-peshev** [comment] 2020-03-03 09:08
Yes you can use bootstrap

**Comment by ZornitsaSerbezova** [comment] 2020-07-06 15:40
I'll close this issue, but feel free to reoen it if needed, explaining what is the problem with an example.

**Closed by ZornitsaSerbezova** 2020-07-06 15:40 UTC
