### ISSUE TITLE
Not working on ie on Local

### ISSUE THREAD

**Issue by MunkhdelgerMorhous** [BALKANGraph/OrgChartJS#208] opened 2019-09-13 04:51 UTC
There is bug on localStorage.getItem("funcUrl"), Also indexed db not working

**Comment by plamen-peshev** [comment] 2019-09-13 07:09
The issue has been addressed

Download latest version 5.0.1 and give it a try

**Comment by MunkhdelgerMorhous** [comment] 2019-09-13 09:08
thanks did just change 3 minutes ago or i tried old ones?

**Comment by plamen-peshev** [comment] 2019-09-13 09:10
The issue is fixed in versions 5.0.1 and 5.0.2

**Closed** 2019-11-28 15:31 UTC
