### ISSUE TITLE
Percentage and Line Overlapped 

### ISSUE THREAD

**Issue by chenxu7601257** [BALKANGraph/OrgChartJS#432] opened 2020-08-20 03:39 UTC
We found an issue that the percentage number and the line are overlapped. Could you fix it? Thanks. 

![image](https://user-images.githubusercontent.com/19574070/90714200-b32be380-e2d9-11ea-8518-a68919a1636a.png)

**Comment by ZornitsaSerbezova** [comment] 2020-08-20 10:08
Hi Jacob,

Could you please tell us what is this percentage? Is it a label on the main line or something else?
It would be good it you can isolate a small example in jsfiddle or an html file with this issue.

**Comment by ZornitsaSerbezova** [comment] 2020-09-18 16:45
As far as I know the issue is fixed, so I'll close it.

**Closed by ZornitsaSerbezova** 2020-09-18 16:45 UTC
