### ISSUE TITLE
Scrollbars are visible when they are not needed

### ISSUE THREAD

**Issue by ZackHJ** [BALKANGraph/OrgChartJS#294] opened 2019-12-06 20:36 UTC
If you set `showXScroll` or `showYScroll` to `OrgChart.scroll.visible`, the scroll bar will always present even when they are not needed (the chart fits in the screen). 
Can you change the `overflow-x` and `overflow-y` to `auto` instead of `scroll` ? Or provide an option to set it?
I believe the locations that the changes should happen are in line 8924 and 9118 (v.6.1.3)
Thanks

**Comment by ZornitsaSerbezova** [comment] 2019-12-09 10:03
Hi Zack,

We have added this in our to do list.

**Comment by ZackHJ** [comment] 2020-02-26 16:41
> Hi Zack,
> 
> We have added this in our to do list.

Any updates on this issue ?

**Comment by ZornitsaSerbezova** [comment] 2020-02-28 09:11
Hi Zack, 

It turned out that the problem is complex, so we'll continue working on it.

**Comment by ZornitsaSerbezova** [comment] 2020-02-28 09:43
Now it is fixed.

**Comment by ZornitsaSerbezova** [comment] 2020-07-06 15:17
I am closing this isuue, but feel free to reopen it if needed.

**Closed by ZornitsaSerbezova** 2020-07-06 15:17 UTC

**Comment by nbpro** [comment] 2020-07-10 08:49
@ZornitsaSerbezova what is the fix version. can you also pass commit id

**Comment by ZornitsaSerbezova** [comment] 2020-07-10 09:15
https://github.com/BALKANGraph/OrgChartJS/releases/tag/6.2.58
You could be able to use the latest verion also.
